# Use the official FreeSWITCH image as base
FROM safarov/freeswitch:latest

# Set environment variables
ENV FS_EXTERNAL_IP=127.0.0.1

# Copy custom configuration files
COPY freeswitch_config/ /etc/freeswitch/

# Expose necessary ports
EXPOSE 5060/udp 5060/tcp 8021/tcp 16384-16484/udp

# Default command
CMD ["/usr/bin/freeswitch", "-c"]